config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :destroy]
  
  resources :comments, except: [:new]
  get '/comments/new/:number', to: 'comments#new' , as: 'new_comment' 
  

  resources :users, except: [:destroy]
  #get '/gossip/:gossip', to: 'static#gossip_page'
  resources :gossip do
    resources :likes 
  end
  
  root 'sessions#new', to: 'sessions#new', as: 'new_session'

  post '/gossip', to: 'gossip#create', as: 'gossip_post' 
  
  resources :city, only: [:index, :show]

  get '/contact', to: 'static#contact'

  get '/team', to: 'static#team'
  
  #get '/user/:user_first_name', to: 'static#user', as: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content,
  presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_attributions
  has_many :comments
  has_many :tags, through: :gossip_tag_attributions
  has_many :likes , dependent: :destroy
  validates :title,
  presence: true,
  length: {minimum:3,maximum:14}
  validates :content,
  presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_attributions
  has_many :gossips, through: :gossip_tag_attributions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
  belongs_to :city
  #has_secure_password 
  #validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.update(user: current_user)
    respond_to do |format|
      if @gossip.save
        format.html { redirect_to '/gossip', notice: "Gossip was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    respond_to do |f|
      if @gossip.update(gossip_params)
        f.html { redirect_to '/gossip', notice: "Gossip was successfully updated." }
      else
        f.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.user_id != current_user.id
      flash.now[:alert] = "Email or password is invalid"
    else
      @gossip.destroy
    end
    redirect_to '/gossip'
  end
  
  private
  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossip/destroy.html.erb
3  <%= flash[:errors] %>

app/views/gossip/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card my-4">
        <h5 class="card-header">Intro</h5>
          <div class="card-body">
            <p class="card-text"><a href="<%=gossip_index_path%>"> Revenir à la liste des potins</a>
          </div>
      </div>
    </div>

    <div class="col-md-8">
      <h1 class="my-4">Editer le potin</h1>
        <div class="card mb-4">
          <div class="card-body">
            <%= form_for @gossip do |f| %>
            <p class="card-title"><div class="form_group">Titre </p><%= f.text_field :title %></div>
            <p class="card-title"><div class="form_group" >Contenu </p><%= f.text_field :content %></div>  
            <br><div class="form-group"><%= f.submit %></div>
              <% end %>
            </div>
      </div>
    </div>
  </div>
</div>

app/views/gossip/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

    <%= yield %>
</div>

<body>

<div class="container">
  <div class="row">
  <% @gossips.each do |gossip| %> 
    <div class="col-sm-6 card-deck">
    <div class="card mb-3" style="width: 20rem; text-align: center">
      <div class="card-body">
        <h5 class="card-title"><%= gossip.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted">by :<%= User.find(gossip.user_id).first_name %></h6>
            <p class="card-text"><%= gossip.content %></p>
            <a href="<%= gossip_path(gossip.id) %>" class="card-link btn btn-dark">Show</a>
            <% if gossip.user_id == current_user.id %>
              <a href="<%= edit_gossip_path(gossip.id) %>" class="card-link btn btn-primary">Edit</a>
            <% else %>
              <a href="<%= gossip_index_path %>" class="card-link btn btn-primary">Edit</a>
            <% end %>
            <a href="<%= gossip_path(gossip.id) %>" data-confirm="Êtes-vous sûr ?" data-method="DELETE" class="card-link btn btn-danger" >Delete</a></p> 
            <br> <%=Like.where(gossip_id:gossip.id).length %>  
            <!-- <%= button_to 'Like', gossip_likes_path(gossip), method: :post %> -->
            <% pre_like = gossip.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
            <%= button_to 'Unlike', gossip_like_path(gossip, pre_like), method: :delete %>
            <% else %>
            <%= button_to 'Like', gossip_likes_path(gossip), method: :post %>
            <% end %>
      </div>
    </div>
    </div>
  <% end %>   
  </div>
  <div class="left_a" style="margin-right:10px;"><a href="<%= new_gossip_path%>" class ="btn btn-light">Créer un potin</a></div>
  <a href="<%= session_path(session[:user_id]) %>" data-confirm="Êtes-vous sûr ?" data-method="DELETE" class="card-link btn btn-danger" >Disconnect</a></p>   
  <% if current_user %>
  
<% end %>
Logged in as <%= current_user.email %>
</div>

app/views/gossip/new.html.erb
<div class="container">
            <div class="row">
            <!-- Side widgets-->
                <div class="col-md-4">
                    <!-- Intro widget-->
                    <div class="card my-4">
                        <h5 class="card-header">Intro</h5>
                        <div class="card-body">
                          <p class="card-text"><a href="<%=gossip_index_path%>"> Revenir à la liste des potins</a>
                        </div>
                    </div>
                </div>

                <!-- Blog entries-->
                <div class="col-md-8">
                    <h1 class="my-4">Créer un potin</h1>
                    <!-- Blog post-->
                    <div class="card mb-4">
                        <div class="card-body">
                        <%= form_for @gossip, url: {action: "create"} do |f| %>
                        Auteur<br>
                        <div class="form_group">
                          <%= f.text_field :title %>
                        </div>
                        Gossip:
                        <div class="form_group">
                          <%= f.text_area :content %>
                        </div>
                        <div class="form_group">
                          <%= f.submit "Create" %>
                        </div>
                      <% end %>
                            <h2 class="card-title">
                            <p class="card-text"></p>
                            <p class="card-text"></p>
                            <p class="card-text"></a></p>
                        </div>
                        </div>
                </div>
                
            </div>
        </div>

  </div>

app/views/gossip/show.html.erb
<div class="container">
            <div class="row">
            
                <div class="col-md-4">

                    <div class="card my-4">
                        <h5 class="card-header">Intro</h5>
                        <div class="card-body">
                          <p class="card-text"><a href="<%=gossip_index_path%>"> Revenir à la liste des potins</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-8">
                    <h1 class="my-4">Le potin en détail</h1>
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title"><%= @gossip.title %></h2>
                            <p class="card-text"><p><%= @gossip.content %></p>
                            <p class="card-text"><a href="<%=user_path(@gossip.user_id)%>" ><%= User.find(@gossip.user_id).first_name %></a></p>
                            <p class="card-text"><a href="<%=city_path(User.find(@gossip.user_id).city_id) %>" ><%= City.find(User.find(@gossip.user_id).city_id).name %></a></p>
                        </div>
                        <div class="card-footer text-muted">
                            Created at 
                        </div>
                    </div>
                    <%= link_to 'New Comment', new_comment_path %>

                <div class="row">
                  <div class="col-sm-3">
                    <div class="well">
                    <% Comment.where(gossip_id: @gossip.id ).each do |comment| %> 
                    <p><%= User.find(comment.user_id).first_name %></p>
                    </div>
                  </div>
                  <div class="col-sm-9">
                    <div class="well">
                    
                  <h5 class="card-title"></h5>
                      <p class="card-text"><%= comment.content %></p>
                      <a href="<%=edit_comment_path(comment.id) %>" >Edit</a> 
                      <a href="<%= comment_path(comment.id) %>" data-confirm="Êtes-vous sûr ?" data-method="DELETE">Delete</a>
                      <a href="../comments/new/<%=params[:id]%>">New Comment</a>
                      <% end %>
                      </div>
                
                    <ul class="pagination justify-content-center mb-4">
                        <li class="page-item"><a class="page-link" href="#!">← Older</a></li>
                        <li class="page-item disabled"><a class="page-link" href="#!">Newer →</a></li>
                    </ul>
                </div>
                
            </div>
        </div>

  </div>