config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :destroy]
  
  resources :comments, except: [:new]
  get '/comments/new/:number', to: 'comments#new' , as: 'new_comment' 
  

  resources :users, except: [:destroy]
  #get '/gossip/:gossip', to: 'static#gossip_page'
  resources :gossip do
    resources :likes 
  end
  
  root 'sessions#new', to: 'sessions#new', as: 'new_session'

  post '/gossip', to: 'gossip#create', as: 'gossip_post' 
  
  resources :city, only: [:index, :show]

  get '/contact', to: 'static#contact'

  get '/team', to: 'static#team'
  
  #get '/user/:user_first_name', to: 'static#user', as: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  validates :content,
  presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_attributions
  has_many :comments
  has_many :tags, through: :gossip_tag_attributions
  has_many :likes , dependent: :destroy
  validates :title,
  presence: true,
  length: {minimum:3,maximum:14}
  validates :content,
  presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_attributions
  has_many :gossips, through: :gossip_tag_attributions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
  belongs_to :city
  #has_secure_password 
  #validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_gossip
                
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @gossip.likes.create(user_id: current_user.id)
    end
    redirect_to gossip_index_path
  end
  before_action :find_like, only: [:destroy]

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to gossip_index_path
  end
  
  private
  def find_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end
  
  def already_liked?
    Like.where(user_id: current_user.id, gossip_id: params[:gossip_id]).exists?
  end

  def find_like
    @like = @gossip.likes.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: %i[ show edit update destroy ] 
  before_action :authenticate_user, only: [:index]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  #def edit
  #end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.update(city: City.all.sample)
    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  #def update
  #  respond_to do |format|
  #    if @user.update(user_params)
  #      format.html { redirect_to @user, notice: "User was successfully updated." }
  #      format.json { render :show, status: :ok, location: @user }
  #    else
  #      format.html { render :edit, status: :unprocessable_entity }
  #      format.json { render json: @user.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /users/1 or /users/1.json
  #def destroy
  #  @user.destroy
  #  respond_to do |format|
  #    format.html { redirect_to users_url, notice: "User was successfully destroyed." }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :email, :description,:password)
    end

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/user.html.erb
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>The Gossip Project</title>
    </head>

<!-- Barre de navigation -->
        <body>
            <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-info">
                <a class="navbar-brand" href="/accueil">The Gossip Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/gossips/new/">Créer un potin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/team">Team</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">Contact</a>
                    </ul>
                </div>
            </nav>

<!-- Jumbotron USER -->
<section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Hello <%= params[:user_first_name] %>!</h1>
      <p><%= link_to "Retourne sur la liste des potins", "/../accueil" %></p>
    </div>
</section>

<!-- Content ID - USER -->
<section class="py-5">
            <div class="container">
                <h1 class="mb-4">Quelques mots sur toi</h1>
                <div class="row">
                    <div class="col-lg-4 mb-4 mb-lg-0">
                        <div class="card h-100">
                            <h4 class="card-header">Ton compte</h4>
                            <div class="card-body"><p class="card-text">Ton nom <%= User.where(first_name:params[:user_first_name]).map{|u| u.last_name}.join %>
                            <br> Ton prénom :<%= params[:user_first_name]%> </p></div>
                        </div>
                    </div>
                    <div class="col-lg-8 mb-4 mb-lg-0">
                        <div class="card h-100">
                            <h4 class="card-header">Ta vie sur le Gossip Project</h4>
                            <div class="card-body"><p class="card-text">
                            Le nombre de gossip que tu as écrit : <%= Gossip.where(user_id:User.where(first_name:"#{params[:user_first_name]}").map{|u| u.id}.join).map{|u| u.id}.length %>
                            <!-- Cette partie sera à corriger car il peut y'avoir plusieurs users avec le meme prenom -->
                            <br>Le nombre de gossip que tu as modifié :</p></div>
                        </div>
                    </div>
                </div>
            </div>
</section>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
 

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class= "container">
  <%= form_for @user, url: {action: "create"} do |f| %>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputAddress">Prénom</label>
        <%= f.text_field :first_name, class: "form-control mb-3" %>
      </div>
      <div class="form-group col-md-6">
        <label for="inputAddress2">Nom</label>
        <%= f.text_field :last_name, class: "form-control mb-3" %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputAge">Age</label>
        <%= f.number_field :age, class: "form-control mb-3" %>
      </div>
      <div class="form-group col-md-6">
        <label for="inputEmail4">Email</label>
        <%= f.text_field :email, class: "form-control mb-3" %>
      </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputPassword4">Password</label>
        <%= f.password_field :password, class: "form-control mb-3" %>
      </div>
      <div class="form-group col-md-6">
        <button type="submit" class="btn btn-primary">Valider</button>
      </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card my-4">
        <h5 class="card-header">Intro</h5>
          <div class="card-body">
            <p class="card-text"><strong>Prénom :</strong> <%= @user.first_name %>
            <p class="card-text"><strong>Nom :</strong> <%= @user.last_name %>
            <p class="card-text"><strong>Âge :</strong> <%= @user.age %>
            <p class="card-text"><strong>Email :</strong> <%= @user.email %>
            <p class="card-text"><strong>Ville :</strong> <a href="<%=city_path(@user.city_id)%>"><%= City.find(@user.city_id).name %></a>
            <br><br><strong>Description :</strong> <%= @user.description %>
            <p class="card-text"><%= link_to 'Revenir à la liste', '/gossip' %>
          </div>
      </div>
    </div>

    <div class="col-md-8">
      <h1 class="my-4">Les potins</h1>
        <div class="card mb-4">
          <div class="card-body">
            <h2 class="card-title">Titre du Gossip</h2>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
          </div>
          <div class="card-footer text-muted">
            Created at :
          </div>
        </div>

    <ul class="pagination justify-content-center mb-4">
      <li class="page-item"><a class="page-link" href="#!">← Older</a></li>
      <li class="page-item disabled"><a class="page-link" href="#!">Newer →</a></li>
    </ul>
    </div>
  </div>
</div>